### PR TITLE
build barebones html and css

### PR DESCRIPTION
**Pull request by natemking**

### CODE REVIEW

**Comment by natemking** [comment]
Reviewed code and approve for main merge

**Comment by dmitriso** [comment]
Reviewed code approved!

**Review by dmitriso — COMMENTED** [review]
Reviewed approved

**Review by natemking — COMMENTED** [review]
Reviewed code and approve add to main.

**Review by dmitriso — APPROVED** [review]
Reviewed approve

**Review by jkhauth — APPROVED** [review]

**Pull request merged**
